sudo: required

language: python
python: 
  - "3.6"

env:
  global:
    - IMAGE_NAME=airflow-docker  

addons:
  atp:
    packages:
      - docker-ce

services:
  - docker
before_install:
  - docker --version

install:
  - docker build -t ${IMAGE_NAME} .
  
script:
  - docker run ${IMAGE_NAME} version | grep "1.10.0"

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWD

deploy:
  provider: script
  script: 
    - deploy-docker.sh