language: python
python: 
  - "3.6"

env:
  global:
    - IMAGE_NAME=airflow-docker  

addons:
  atp:
    packages:
      - docker-ce

services:
  - docker
before_install:
  - docker --version

install:
  - docker build -t airflow-docker .
  
script:
  - docker run airflow-docker version | grep `1.10.0`

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWD"
  - docker tag "$IMAGE_NAME" "$DOCKER_USER/${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "$DOCKER_USER/${IMAGE_NAME}:latest"
  on:
    branch: master